version: "3"

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    container_name: "mongodb-udemy-spring-webflux"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_DATABASE=manual_review
    ports:
      - "27017:27017"
    # volumes:
    #   - mongodb_data:/bitnami

# volumes:
#   mongodb_data:
#     external: true
